const data= {
    products: [
        {
            _id: '1',
            name: 'Alienware m15',
            category: 'Laptops',
            image: '/images/p1.jpg',
            price: 1350,
            countInStock: 10,
            brand: 'Dell',
            rating: 5,
            numReviews: 10,
            description: 'High performance laptop',
        },
        {
            _id: '2',
            name: 'Asus Rog',
            category: 'Laptops',
            image: '/images/p2.jpg',
            price: 1450,
            countInStock: 12,
            brand: 'Asus',
            rating: 4.5,
            numReviews: 19,
            description: 'High performance laptop',
        },
        {
            _id: '3',
            name: 'Dell Latitude 5410',
            category: 'Laptops',
            image: '/images/p3.jpg',
            price: 1550,
            countInStock: 15,
            brand: 'Dell',
            rating: 5,
            numReviews: 28,
            description: 'High performance laptop',
        },
        {
            _id: '4',
            name: 'HP ProBook',
            category: 'Laptops',
            image: '/images/p4.jpg',
            price: 1100,
            countInStock: 20,
            brand: 'HP',
            rating: 3.5,
            numReviews: 8,
            description: 'High performance laptop',
        },
        {
            _id: '5',
            name: 'Lenovo Region 5i',
            category: 'Laptops',
            image: '/images/p5.jpg',
            price: 1450,
            countInStock: 18,
            brand: 'Lenovo',
            rating: 4.8,
            numReviews: 30,
            description: 'High performance laptop',
        },
        {
            _id: '6',
            name: 'Lenovo IdeaPad',
            category: 'Laptops',
            image: '/images/p6.jpg',
            price: 1400,
            countInStock: 0,
            brand: 'Lenovo',
            rating: 4.7,
            numReviews: 20,
            description: 'High performance laptop',
        },
    ],
};
export default data;